### PR TITLE
Change rsspp::item and rsspp::feed to classes with default constructor

### PR DESCRIPTION
**Pull request by gpakosz**

### CODE REVIEW

**Comment by gpakosz** [comment]
I was about to update the previous PR but you already merged it. This is what I should have written in the first place 😕

**Comment by Minoru** [comment]
Sorry about that; I probably should've asked you to ping me when that PR is ready for merge. Will keep that in mind in the future.

As for current changes, I have only one nitpick. Since `feed` now has a constructor, it's no longer "plain old data"—it's a class. In order to make this obvious, please do the following:
* change `struct` to `class` and add `public` after the opening curly bracket;
* move the constructor to the very top (because that's how other classes in the project are declared.)

**Comment by gpakosz** [comment]
Since `feed` has `std::string` members it has never been plain old data to begin with though

**Comment by Minoru** [comment]
I stand corrected. Thanks!

**Comment by gpakosz** [comment]
I made the requested changes for `rsspp::feed`. Should I do the same for `rsspp::item`? It seems to me `item.guid_isPermaLink` and `item.pubDate_ts` could suffer from the same uninitialized value situations

**Comment by Minoru** [comment]
That'll be very nice of you! `guid_isPermaLink` better be initialized to 
`false`, because that's safer than assuming that the value inside 
`<guid>` is a valid link. Timestamp can be anything.

**Comment by gpakosz** [comment]
Then this branch and PR name isn't accurate. I can close it and open another. What do you think?

**Comment by Minoru** [comment]
Git doesn't preserve branch names after merge, so you can keep it as it is. The PR itself can be renamed; do you have an "Edit" button next to the title?

I'm replying via email, but I won't be able to merge through it. If you can't edit the title, I'll do it before the merge.

**Comment by gpakosz** [comment]
Well the branch name I choose ends up in the commit log :)
```
Merge pull request #555 from gpakosz/valgrind
```

**Comment by Minoru** [comment]
Ah, right, the commit log. I don't think this matters, but if you want, I can simply delete the branch name from the commit text. Creating a separate PR seems like overkill; I don't think there's ever a valid situation to do this.

And to make sure I don't merge prematurely like I did with the previous one: are you done with these changes?

**Comment by gpakosz** [comment]
I believe I'm done 🙂

**Comment by Minoru** [comment]
Shit-shit-shit, I clicked the button twice and it confirmed the merge before I could edit the message >_<

**Comment by gpakosz** [comment]
🤣

**Comment by Minoru** [comment]
My ineptness aside, thank you for the PR!

**Comment by gpakosz** [comment]
You're welcome. Happy to give back with this modest contribution

**Pull request merged**
