### PR TITLE
Update fr.po

### PR DESCRIPTION
**Pull request by esteban123456789**
line 667 mistake : "Mark All Read" => "Notez Tous Lus"

### CODE REVIEW

**Comment by Minoru** [comment]
Just to be sure: do you understand that "mark all read" means "all unread items should become read"? I can see how "non-lus" could be correct if "notez" were translated as "mark down" or "toggle".

I'm going to merge this if you say it's correct; just want to make sure you aren't making a mistake.

Thank you for the PR!

**Comment by esteban123456789** [comment]
On Thu, 27 Apr 2017 10:29:24 -0700
Alexander Batischev <notifications@github.com> wrote:

> Just to be sure: do you understand that "mark all read" means "all unread items should become read"? I can see how "non-lus" could be correct if "notez" were translated as "mark down" or "toggle".
> 
> I'm going to merge this if you say it's correct; just want to make sure you aren't making a mistake.
> 
> Thank you for the PR!
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/akrennmair/newsbeuter/pull/542#issuecomment-297784037

Hi Alexander,

Thank you to reply.

Of course, I am sure : I am a french native.

It is very disruptive to see the inverse.

"mark all read" means "all unread items should become read" !
but it's depend if we talk about the items or the status


For the items, literally, "mark all read" translates into "marquez tous lus" (better) or "notez tous lus"

Sometimes some mistake happends...

I would like to thank you and the contributors for your work

Have a nice day

You're welcome

-- 
Estéban Fernandez <Em9b@noos.fr>

**Comment by esteban123456789** [comment]
Hi Alexander,

Thank you to reply.

Of course, I am sure : I am a french native.

It is very disruptive to see the inverse.

"mark all read" means "all unread items should become read" !
but it's depend if we talk about the items or the status

For the items, literally, "mark all read" translates into "marquez tous lus" (better) or "notez tous lus"

Sometimes some mistake happends...

I would like to thank you and the contributors for your work

Have a nice day

You're welcome

**Comment by Minoru** [comment]
Oh, I wasn't questioning your knowledge of French—I only wanted to make sure you understand the English version correctly. I'm satisfied now; will merge in a moment. Thank you!

Perhaps you'll be interested in translating a few missing messages? We have a five or so. You can also grep for "fuzzy": these are messages that might be out of date; you remove the tag from the messages that you checked, and update the ones that are broken.

**Comment by esteban123456789** [comment]
OK
I'll see as soon as I have a little time.

**Pull request merged**
