### PR TITLE
Already read items still appear in search results as unread

### PR DESCRIPTION
**Pull request by ahitrin**
Newsbeuter is pretty and very useful for me, but, unfortunately, it suffers from some small bugs. One of this bugs annoys me very much. It can be reproduced very easily:

 * start a search in an RSS feed
 * read some articles
 * quit search
 * run new search

And voila! You can see your read articles **again**, marked as _unread_, among with other articles that are relevant to the search string.

I tried hard to create working UI test that demonstrates this, and after all, here it is. Here I start a search that finds two articles (31), read one of these articles (39), reset a search (45) and start a new one (56). After that I expect that already read item should not be shown (60). But it is.

Here is a test log:

    I: On (1,3), found `1 N  Aug 30   212   |RSS 2.0 testbed f|  RSS 2.0 Item 1' as expected.
    I: On (1,3), found `1    Aug 30   212   |RSS 2.0 testbed f|  RSS 2.0 Item 1' as expected.
    I: On (2,3), found `2 N  Aug 28   170   |RSS 2.0 testbed f|  RSS 2.0 Item 3' as expected.
    E: On (1,3), expected `1 N  Aug 28   170   |RSS 2.0 testbed f|  RSS 2.0 Item 3', but found `1 N  Aug 30   212   |RSS 2.0 testbed f|  RSS 2.0 Item 1'

Unfortunately, I'm not able to fix this issue yet, but I hope that working test could help identify root cause of this issue, Therefore, I just provide a test at this time. I hope this issue could be fixed!

### CODE REVIEW

**Comment by cambid** [comment]
@akrennmair Could you please merge this pull request and release a new version of newsbeuter?

**Comment by Minoru** [comment]
Hi. Thought I'd chime in and explain why this hasn't been merged over the last half a year that I've been maintaining the codebase.

The work is incomplete, as the author himself mentioned in his last comment. I focused my attention on issues for now, but I'll look into this one eventually. If you're interested, you can complete the patches—reviewing complete PRs is much less work than fixing bugs, so I'll be able to merge it pretty quickly.

As for the release, I've put 2.10 together a while ago, but @akrennmair hasn't gotten around to releasing it yet. Looking forward to it just as much as you do!

**Comment by ahitrin** [comment]
So, first of all I need to check whether this bug appears in new versions. Please give me some time to take a look at code.

**Comment by ahitrin** [comment]
My investigation reveals that the first attempt to fix the bug was really crappy. So I've started from the very beginning and found much simpler solution. Please take a look at #339. I think, current pull request should be closed now.

@cambid @Minoru thank you for the ping!

**Pull request closed without merging**
