### PR TITLE
Fix newsblur

### LINKED ISSUE #261: HEAD crushes with Newsblur
The following config:
```
newsblur-login "LOGIN"
newsblur-password "PASSWORD"
urls-source "newsblur"
cookie-cache "/home/minoru/.newsbeuter/cookies.txt"
```
makes HEAD crash:
```
XDG: configuration directory '/home/minoru/.config/newsbeuter' not accessible, using '/home/minoru/.newsbeuter' instead.
Starting newsbeuter 2.10...
Loading configuration...done.
Opening cache...done.
Loading URLs from NewsBlur...zsh: segmentation fault  ./newsbeuter -c cache.db -C config -u urls -l6 -dnewsbeuter.log
```

Log shows that Newsbeuter successfully logs into Newsblur and retrieves data from https://newsblur.com/reader/feeds/

### PR DESCRIPTION
**Pull request by t-8ch**
Fixes #261
Cc: @aniranc

### CODE REVIEW

**Comment by Minoru** [comment]
Thanks!

Should I take it that you didn't check if tags part of Newsblur's API changed since our 2.9 release? To figure out if this was our bug, or just the change to a third-party service.

The trouble with Travis seem transient, but persisted for 7 hours now. Will try again in the morning.

**Comment by t-8ch** [comment]
I never looked how tags in Newsblur or newsbeuter worked and hoped instead @aniranc had some insights and would fix it. Maybe I will find on the weekend for a proper fix if no one else beats me to it.

**Comment by Minoru** [comment]
Builds were failing due to llvm.org disabling their APT mirror. Ignore Clang on Linux failures (you can rebase on top of master to get an update to `.travis.yml` that will disable them).

**Comment by Minoru** [comment]
Looked into it myself. So the problem is that NewsBlur returns a list of folders where each folder is an dictionary, *but* this list also includes IDs of feeds that don't belong to any folder, like this:

````
"folders": [{"foldername": [1,2,3,4]}, 5, 6]
````

And the fix you provide will just skip 5 and 6 above. That seems reasonable, so I'll merge it. Thank you for your work!

(There's also an issue with nested folders, which I reported separately—see #318.)

**Pull request merged**
