### PR TITLE
Don't use tabs for alignment

### PR DESCRIPTION
**Pull request by tsipinakis**
The width of the tab character varies from setup to setup which breaks
alignment. Using spaces is better since it has a standard length.

### CODE REVIEW

**Comment by Minoru** [comment]
I think it's ugly either way. The lines are very long and make it hard to read and edit. I'm not sure how exactly people read this thing, so it's impossible for me to figure out the best way to reformat it.

So I went with general readibility, which means making lines shorter and grouping similar things together:
```c++
{
	OP_OPEN, "open", "ENTER",
	_("Open feed/article"),
	KM_FEEDLIST | KM_FILEBROWSER | KM_HELP | KM_ARTICLELIST | KM_TAGSELECT
		| KM_FILTERSELECT | KM_URLVIEW | KM_PODBEUTER | KM_DIALOGS
},

// Spelling our tabs so you understand where I use them.
{
>---OP_QUIT, "quit", "q",
>---_("Return to previous dialog/Quit"),
>---KM_FEEDLIST | KM_FILEBROWSER | KM_HELP | KM_ARTICLELIST | KM_ARTICLE
>--->---| KM_TAGSELECT | KM_FILTERSELECT | KM_URLVIEW | KM_PODBEUTER
>--->---| KM_DIALOGS
},
```

What do you think?

JFTR: I'll merge this after #380, just on a principle: let's not make people resolve merge conflicts caused by later PRs. You cool with that?

**Comment by tsipinakis** [comment]
> I think it's ugly either way. The lines are very long and make it hard to read and edit. I'm not sure how exactly people read this thing, so it's impossible for me to figure out the best way to reformat it.

I have a pretty wide monitor so except for the first few keymaps all the rest can be displayed in one line which helps a lot in the readability so I never had a problem reading that file, tho I can imagine it can be a pain to read in other situations.

The format you proposed does seem to have a lot better readability in situations where you can't see the entire line at once. So I am in favour of switching to that.

If you also agree with that, I can update the PR.

> I'll merge this after #380, just on a principle: let's not make people resolve merge conflicts caused by later PRs

Thats fine, I'll fix the merge conflicts once #380 is merged.

**Comment by Minoru** [comment]
> I have a pretty wide monitor so except for the first few keymaps all the rest can be displayed in one line

I do too, but I normally have two vertical Vim splits open, which halves the line width. That's actually one of the reasons I still believe in "80 characters per line" thing.

> If you also agree with that, I can update the PR.

That'll be cool. Thanks!

Also I just realised that my latest commit changed `src/keymap.cpp`, causing conflicts both for you and #380… My silliness sometimes surprise even me :)

**Comment by tsipinakis** [comment]
Changed the keymap file to use the new format, let me know if theres any other changes needed.

**Comment by Minoru** [comment]
Now short stuff like "Open URL 5" looks ugly :) But mixing styles will confuse it all. Oh well, you did everything you can, and I believe it's better than before.

Thanks for working on this! Let's wait for #380 now.

**Comment by Minoru** [comment]
Okay, #380 is merged; please update your PR.

**Comment by Minoru** [comment]
Thank you!

**Pull request merged**
