### PR TITLE
build: Fix build on GCC 8

### PR DESCRIPTION
**Pull request by Elv13**
There is a narrowing Werror for size_t

### CODE REVIEW

**Comment by Minoru** [comment]
Hi! Newsbeuter is no longer maintained, but this bug [have already been fixed](https://github.com/newsboat/newsboat/commit/0a94da8e729c55b61ba87233a789497276bb791e) in the fork I lead, Newsboat. We do have a load of other bugs though, so if you're itching to fix some, check out our issue tracker :) (And we also accept pull requests that fix any of Newsbeuter's bugs)

**Comment by Elv13** [comment]
I know, but given this version is available on more platforms and doesn't require rust, I think it is worth keeping up to date with compiling errors or at least removing -Werror so it doesn't break with new compiler releases. There is some retro-computing scenarios where Newsboat probably wont ever be available. Of course those platforms are not likely to have GCC8+, so this argument is a bit moot. Still, it's a one liner.

**Comment by Minoru** [comment]
> I think it is worth keeping up to date

Then you need to fork it and maintain the fork. There is no-one who can merge this change (I stepped down and repo owner is absent), and no-one who would hand you the keys to this repo (I don't have the access, and repo owner is absent).

If you go that route, please check out the link I gave above. The build failure has nothing to do with GCC 8. And consider forking Newsboat 2.13 instead, as it contains some bug fixes relative to Newsbeuter's master branch.

**Comment by Elv13** [comment]
ok then

**Pull request closed without merging**
