### PR TITLE
Make cursor visible when in a cmdline

### PR DESCRIPTION
**Pull request by sometoby**
This fixes the oversight in #379.

### CODE REVIEW

**Comment by Minoru** [comment]
While testing, I also found a number of other places where it makes sense to show the cursor:
* search dialog
* goto-url
* bookmark
* edit-flags

We have a thingy called QNA somewhere in the `view.cpp` IIRC—it's responsible for things like that. Can you patch it as well?

**Comment by tsipinakis** [comment]
Theres `formaction::start_qna` and `formaction::finished_qna` in `formaction.cpp`, setting the cursor visibility there would probably be the cleanest solution.

**Comment by sometoby** [comment]
There we go, that should do it. Apologies for my lackluster testing.

**Comment by Minoru** [comment]
I broke it :) `?/<Enter>`, i.e. open help dialog, start a search, press Enter. The cursor stays on. If I enter search again and press Escape, the cursor disappears.

The rest of stuff I listed before works properly.

**Comment by Minoru** [comment]
To be clear on what's going on: are you looking/will look into this, @sometoby?

**Comment by sometoby** [comment]
Fixed that too!

**Comment by Minoru** [comment]
Yes you did! Just tested it all.

**Comment by sometoby** [comment]
Podbeuter still needs to have this fix applied seperately, I'll look into that later.

**Comment by Minoru** [comment]
Did you have a chance to look into updating Podbeuter yet?

I'm thinking of merging this PR as-is to fix Newsbeuter, and opening a separate, Podbeuter-specific issue that can be closed later with another PR. What do you think?

**Comment by Minoru** [comment]
> I'm thinking of merging this PR as-is to fix Newsbeuter, and opening a separate, Podbeuter-specific issue that can be closed later with another PR.

Going through with this because this will allow me to finally bring `{ordinary,fancy}-changelog` branches up to date with the master.

I'm re-opening #344 to remind us that Podbeuter part isn't done yet.

**Comment by Minoru** [comment]
And last but not least: thanks for working on this!

**Pull request merged**
