### PR TITLE
Corrected Pocket redirection URL

### PR DESCRIPTION
**Pull request by vaygr**
This one fixes a 404 during access token generation.

### CODE REVIEW

**Comment by Minoru** [comment]
I'd rather see this referencing specific commit rather than master branch. This way we can have version-specific messages, and also perform refactorings without breaking anything for existing users.

**Comment by vaygr** [comment]
How'd we get the commit that hasn't been made yet?

**Comment by Minoru** [comment]
Use the one that most recently changed the file, i.e. c8c92a17.

**Comment by vaygr** [comment]
Oh, not just the latest one, got it. Good point.

**Comment by Minoru** [comment]
Thanks!

**Pull request merged**
