### PR TITLE
Add catalan translation

### PR DESCRIPTION
**Pull request by alejandrogallo**
I've seen there is no catalan translation.

Here is an almost complete translation, I took the spanish translation as an
example.  There may be a couple of sentences still in spanish, but since
everyone who speaks catalan also speaks spanish, that should not be a problem.

### CODE REVIEW

**Comment by Minoru** [comment]
Wow! I've seen some huge translation updates, but this is the first time I see a whole new language added. This is an insane amount of work! Thank you very, very much! Will merge as soon as Travis finishes its thing (I don't expect any surprises there, but you never know.)

**Comment by Minoru** [comment]
i18nspector [found a few problems](https://travis-ci.org/akrennmair/newsbeuter/jobs/253143669#L499) with the translation file, can you please fix them? The errors seem self-explanatory, but if you bump into any troubles, feel free to ask—maybe they only *seem* easy to me.

**Comment by Minoru** [comment]
@alejandrogallo, do you need any help? Ask away! ;)

**Comment by alejandrogallo** [comment]
Hi I'm sorry, I had a lot to do and I kept on postponing it
I think it should be fixed now, I did a

`make run-i18nspector`

and it should work, apparently it wants `ca` as the language identifier instead
of `cat`. Let's see what travis says  ;)

**Comment by Minoru** [comment]
Travis is happy and so am I ^_^ Thanks once again for a great piece of work!

**Pull request merged**
